# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 08:26
from __future__ import unicode_literals

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summernote',
            name='tag',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
    ]
