# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_summernote_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summernote',
            name='tag',
        ),
    ]
