# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_summernote_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='summernote',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='제목'),
            preserve_default=False,
        ),
    ]
