# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='행사명')),
                ('event_date', models.DateTimeField(verbose_name='행사일시')),
                ('fee', models.CharField(choices=[('free', '무료'), ('paid', '무료')], max_length=10, verbose_name='참가비')),
                ('location', models.CharField(max_length=200, verbose_name='행사장소')),
                ('link', models.URLField(blank=True, verbose_name='링크')),
                ('description', models.TextField(verbose_name='행사내용')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category_set', models.ManyToManyField(to='info.Category')),
            ],
        ),
    ]
