# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='info',
            name='category_set',
            field=models.ManyToManyField(related_name='분야', to='info.Category'),
        ),
        migrations.AlterField(
            model_name='info',
            name='fee',
            field=models.CharField(choices=[('free', '무료'), ('paid', '유료')], max_length=10, verbose_name='참가비'),
        ),
    ]
